function Jstdot = auto_Jstdot(l1,l2,q1,q2,q1dot,q2dot)
%auto_Jstdot
%    Jstdot = auto_Jstdot(L1,L2,Q1,Q2,Q1DOT,Q2DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 13:46:45

t2 = -q2;
t3 = q1+t2;
t4 = cos(t3);
t5 = sin(t3);
t6 = l2.*q2dot.*t4;
t7 = l2.*q2dot.*t5;
Jstdot = [-q2dot.*(t7-l2.*q1dot.*t5)+q1dot.*(t7-q1dot.*(l2.*t5+l1.*sin(q1)));-q2dot.*(t6-l2.*q1dot.*t4)+q1dot.*(t6-q1dot.*(l2.*t4+l1.*cos(q1)))];
end
