function Jstdot = auto_Jstdot(l1,l2,q1,q2,q1dot,q2dot)
%auto_Jstdot
%    Jstdot = auto_Jstdot(L1,L2,Q1,Q2,Q1DOT,Q2DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 11:46:50

t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = l2.*q2dot.*t3;
t6 = l2.*q2dot.*t4;
Jstdot = [-q2dot.*(t6+l2.*q1dot.*t4)-q1dot.*(t6+q1dot.*(l2.*t4+l1.*sin(q1)));-q2dot.*(t5+l2.*q1dot.*t3)-q1dot.*(t5+q1dot.*(l2.*t3+l1.*cos(q1)))];
end
