function Jst = auto_Jst(l1,l2,q1,q2)
%auto_Jst
%    Jst = auto_Jst(L1,L2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 11:46:50

t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = l2.*t3;
t6 = l2.*t4;
t7 = -t6;
Jst = reshape([1.0,0.0,0.0,1.0,t5+l1.*cos(q1),t7-l1.*sin(q1),t5,t7],[2,4]);
end
