function C = auto_C(d1,d2,l1,m1,m2,q1,q2,q1dot,q2dot)
%auto_C
%    C = auto_C(D1,D2,L1,M1,M2,Q1,Q2,Q1DOT,Q2DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 13:46:44

t2 = cos(q1);
t3 = sin(q1);
t4 = sin(q2);
t5 = -q2;
t6 = -q2dot;
t7 = q1+t5;
t8 = q1dot+t6;
t9 = cos(t7);
t10 = sin(t7);
C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-q1dot.*((m2.*(d2.*t10.*2.0+l1.*t3.*2.0))./2.0+d1.*m1.*t3)+d2.*m2.*q2dot.*t10,-q1dot.*((m2.*(d2.*t9.*2.0+l1.*t2.*2.0))./2.0+d1.*m1.*t2)+d2.*m2.*q2dot.*t9,d2.*l1.*m2.*t4.*t6,d2.*l1.*m2.*q1dot.*t4,d2.*m2.*t8.*t10,d2.*m2.*t8.*t9,-d2.*l1.*m2.*t4.*t8,0.0],[4,4]);
end
