function D = auto_D(I1,I2,d1,d2,l1,m1,m2,q1,q2)
%auto_D
%    D = auto_D(I1,I2,D1,D2,L1,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 11:46:49

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = m1+m2;
t6 = q1+q2;
t7 = d2.^2;
t8 = cos(t6);
t9 = sin(t6);
t10 = d1.*m1.*t2;
t11 = d1.*m1.*t4;
t12 = m2.*t7;
t13 = l1.*t2.*2.0;
t14 = l1.*t4.*2.0;
t15 = d2.*l1.*m2.*t3;
t16 = -t11;
t17 = d2.*t8.*2.0;
t18 = d2.*t9.*2.0;
t19 = d2.*m2.*t8;
t20 = d2.*m2.*t9;
t24 = I2+t12+t15;
t21 = -t20;
t22 = t13+t17;
t23 = t14+t18;
t25 = (m2.*t22)./2.0;
t26 = (m2.*t23)./2.0;
t27 = -t26;
t28 = t10+t25;
t29 = t16+t27;
D = reshape([t5,0.0,t28,t19,0.0,t5,t29,t21,t28,t29,I1+t15+t24+d1.^2.*m1+l1.^2.*m2,t24,t19,t21,t24,I2+t12],[4,4]);
end
