function G = auto_G(d1,d2,g,l1,m1,m2,q1,q2)
%auto_G
%    G = auto_G(D1,D2,g,L1,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 13:46:45

t2 = sin(q1);
t3 = -q2;
t4 = q1+t3;
t5 = sin(t4);
G = [0.0;g.*(m1+m2);-g.*m2.*(d2.*t5+l1.*t2)-d1.*g.*m1.*t2;d2.*g.*m2.*t5];
end
