function G = auto_G(d1,d2,g,l1,m1,m2,q1,q2)
%auto_G
%    G = auto_G(D1,D2,g,L1,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 11:46:49

t2 = sin(q1);
t3 = q1+q2;
t4 = sin(t3);
G = [0.0;g.*(m1+m2);-g.*m2.*(d2.*t4+l1.*t2)-d1.*g.*m1.*t2;-d2.*g.*m2.*t4];
end
