function D = auto_D(I1,I2,d1,d2,l1,m1,m2,q1,q2)
%auto_D
%    D = auto_D(I1,I2,D1,D2,L1,M1,M2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 13:46:44

t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = m1+m2;
t6 = d2.^2;
t7 = -q2;
t8 = d1.*m1.*t2;
t9 = d1.*m1.*t4;
t10 = m2.*t6;
t11 = l1.*t2.*2.0;
t12 = l1.*t4.*2.0;
t13 = d2.*l1.*m2.*t3;
t14 = q1+t7;
t15 = cos(t14);
t16 = sin(t14);
t17 = -t9;
t18 = -t10;
t19 = -t13;
t20 = d2.*m2.*t15;
t21 = d2.*m2.*t16;
t22 = d2.*t15.*2.0;
t23 = d2.*t16.*2.0;
t27 = I2+t18+t19;
t24 = -t20;
t25 = t11+t22;
t26 = t12+t23;
t28 = (m2.*t25)./2.0;
t29 = (m2.*t26)./2.0;
t30 = -t29;
t31 = t8+t28;
t32 = t17+t30;
D = reshape([t5,0.0,t31,t24,0.0,t5,t32,t21,t31,t32,I1+I2+t10+t13.*2.0+d1.^2.*m1+l1.^2.*m2,t27,t24,t21,t27,I2+t10],[4,4]);
end
