function Jst = auto_Jst(l1,l2,q1,q2)
%auto_Jst
%    Jst = auto_Jst(L1,L2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 13:46:45

t2 = -q2;
t3 = q1+t2;
t4 = cos(t3);
t5 = sin(t3);
t6 = l2.*t4;
t7 = l2.*t5;
Jst = reshape([1.0,0.0,0.0,1.0,t6+l1.*cos(q1),-t7-l1.*sin(q1),-t6,t7],[2,4]);
end
