function C = auto_C(d1,d2,l1,m1,m2,q1,q2,q1dot,q2dot)
%auto_C
%    C = auto_C(D1,D2,L1,M1,M2,Q1,Q2,Q1DOT,Q2DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 11:46:49

t2 = cos(q1);
t3 = sin(q1);
t4 = sin(q2);
t5 = q1+q2;
t6 = q1dot+q2dot;
t7 = cos(t5);
t8 = sin(t5);
C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-q1dot.*((m2.*(d2.*t8.*2.0+l1.*t3.*2.0))./2.0+d1.*m1.*t3)-d2.*m2.*q2dot.*t8,-q1dot.*((m2.*(d2.*t7.*2.0+l1.*t2.*2.0))./2.0+d1.*m1.*t2)-d2.*m2.*q2dot.*t7,-d2.*l1.*m2.*q2dot.*t4,d2.*l1.*m2.*q1dot.*t4,-d2.*m2.*t6.*t8,-d2.*m2.*t6.*t7,-d2.*l1.*m2.*t4.*t6,0.0],[4,4]);
end
