function B = auto_B
%auto_B
%    B = auto_B

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Sep-2025 11:46:49

B = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,2]);
end
