function d2h__flight = auto_d2h__flight
%AUTO_D2H__FLIGHT
%    D2H__FLIGHT = AUTO_D2H__FLIGHT

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Oct-2025 09:33:06

d2h__flight = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0],[2,10]);
end
