function G = auto_G(d1,d2,d3,g,l1,m1,m2,m3,q1,q2,q3)
%auto_G
%    G = auto_G(D1,D2,D3,g,L1,M1,M2,M3,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:31

t2 = sin(q1);
t3 = -q2;
t4 = q1+t3;
t5 = sin(t4);
G = [0.0;g.*(m1+m2+m3);g.*m2.*(d2.*t5+l1.*t2)+d1.*g.*m1.*t2;-d2.*g.*m2.*t5;-d3.*g.*m3.*sin(q3)];
end
