function B = auto_B
%auto_B
%    B = auto_B

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

B = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[5,2]);
end
