function d2h__ = auto_d2h__(d1,d2,d3,l1,l2,m1,m2,m3,q1,q2,q3,q1dot,q2dot,q3dot)
%AUTO_D2H__
%    D2H__ = AUTO_D2H__(D1,D2,D3,L1,L2,M1,M2,M3,Q1,Q2,Q3,Q1DOT,Q2DOT,Q3DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

t2 = cos(q1);
t3 = cos(q3);
t4 = sin(q1);
t5 = sin(q3);
t7 = m1+m2+m3;
t9 = -q2;
t6 = l1.*t2;
t8 = l1.*t4;
t10 = d1.*m1.*t2;
t11 = d1.*m1.*t4;
t12 = q1+t9;
t14 = 1.0./t7;
t13 = cos(t12);
t15 = sin(t12);
t16 = d2.*t13;
t17 = l2.*t13;
t18 = d2.*t15;
t19 = l2.*t15;
t20 = t6+t16;
t21 = t8+t18;
t24 = m2.*t14.*t18;
t25 = m2.*q2dot.*t14.*t16;
t22 = m2.*t20;
t23 = m2.*t21;
t26 = -t24;
t27 = t11+t23;
t28 = t10+t22;
t29 = t19+t26;
t30 = t14.*t27;
t31 = q2dot.*t29;
d2h__ = reshape([0.0,0.0,0.0,0.0,t31-q1dot.*(t8+t19-t30),-t25+q1dot.*t14.*t28,-t31+q1dot.*t29,t25-m2.*q1dot.*t14.*t16,d3.*m3.*q3dot.*t5.*t14,-d3.*m3.*q3dot.*t3.*t14,0.0,0.0,0.0,1.0,t6+t17-t14.*t28,t30,-t17+m2.*t14.*t16,t26,-d3.*m3.*t3.*t14,-d3.*m3.*t5.*t14],[2,10]);
end
