function pCOM = auto_pCOM(d1,d2,d3,l1,m1,m2,m3,q1,q2,q3,x,y)
%auto_pCOM
%    pCOM = auto_pCOM(D1,D2,D3,L1,M1,M2,M3,Q1,Q2,Q3,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:31

t2 = cos(q1);
t3 = sin(q1);
t4 = m1+m2+m3;
t5 = -q2;
t6 = q1+t5;
t7 = 1.0./t4;
pCOM = [t7.*(m3.*(x-d3.*sin(q3))+m1.*(x-d1.*t3)-m2.*(-x+l1.*t3+d2.*sin(t6)));t7.*(m3.*(y+d3.*cos(q3))+m1.*(y-d1.*t2)-m2.*(-y+l1.*t2+d2.*cos(t6)))];
end
