function Jhdot = auto_Jhdot(d1,d2,d3,l1,l2,m1,m2,m3,q1,q2,q3,q1dot,q2dot,q3dot)
%auto_Jhdot
%    Jhdot = auto_Jhdot(D1,D2,D3,L1,L2,M1,M2,M3,Q1,Q2,Q3,Q1DOT,Q2DOT,Q3DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

t2 = cos(q1);
t3 = sin(q1);
t4 = m1+m2+m3;
t6 = -q2;
t5 = l1.*t3;
t7 = q1+t6;
t9 = 1.0./t4;
t8 = cos(t7);
t10 = sin(t7);
t11 = l2.*t10;
t12 = d2.*m2.*t9.*t10;
t13 = d2.*m2.*q2dot.*t8.*t9;
t14 = -t12;
t15 = t11+t14;
t16 = q2dot.*t15;
Jhdot = reshape([0.0,0.0,0.0,0.0,t16-q1dot.*(t5+t11-t9.*(m2.*(t5+d2.*t10)+d1.*m1.*t3)),-t13+q1dot.*t9.*(m2.*(d2.*t8+l1.*t2)+d1.*m1.*t2),-t16+q1dot.*t15,t13-d2.*m2.*q1dot.*t8.*t9,d3.*m3.*q3dot.*t9.*sin(q3),-d3.*m3.*q3dot.*t9.*cos(q3)],[2,5]);
end
