function pfoot = auto_pfoot(l1,l2,q1,q2,x,y)
%AUTO_PFOOT
%    PFOOT = AUTO_PFOOT(L1,L2,Q1,Q2,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:31

t2 = -q2;
t3 = q1+t2;
pfoot = [x-l1.*sin(q1)-l2.*sin(t3);y-l1.*cos(q1)-l2.*cos(t3)];
end
