function Lfh_flight = auto_Lfh_flight(q1dot,q2dot)
%auto_Lfh_flight
%    Lfh_flight = auto_Lfh_flight(Q1DOT,Q2DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Oct-2025 09:33:06

Lfh_flight = [q1dot;q2dot];
end
