function JpCOM = auto_JpCOM(d1,d2,d3,l1,m1,m2,m3,q1,q2,q3)
%auto_JpCOM
%    JpCOM = auto_JpCOM(D1,D2,D3,L1,M1,M2,M3,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

t2 = cos(q1);
t3 = sin(q1);
t4 = m1+m2+m3;
t5 = -q2;
t6 = q1+t5;
t8 = 1.0./t4;
t7 = cos(t6);
t9 = sin(t6);
JpCOM = reshape([1.0,0.0,0.0,1.0,-t8.*(m2.*(d2.*t7+l1.*t2)+d1.*m1.*t2),t8.*(m2.*(d2.*t9+l1.*t3)+d1.*m1.*t3),d2.*m2.*t7.*t8,-d2.*m2.*t8.*t9,-d3.*m3.*t8.*cos(q3),-d3.*m3.*t8.*sin(q3)],[2,5]);
end
