function Lfh = auto_Lfh(d1,d2,d3,l1,l2,m1,m2,m3,q1,q2,q3,q1dot,q2dot,q3dot,ydot)
%auto_Lfh
%    Lfh = auto_Lfh(D1,D2,D3,L1,L2,M1,M2,M3,Q1,Q2,Q3,Q1DOT,Q2DOT,Q3DOT,YDOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

t2 = cos(q1);
t3 = sin(q1);
t5 = m1+m2+m3;
t6 = -q2;
t4 = l1.*t2;
t7 = q1+t6;
t9 = 1.0./t5;
t8 = cos(t7);
t10 = sin(t7);
t11 = l2.*t8;
Lfh = [-q2dot.*(t11-d2.*m2.*t8.*t9)+q1dot.*(t4+t11-t9.*(m2.*(t4+d2.*t8)+d1.*m1.*t2))-d3.*m3.*q3dot.*t9.*cos(q3);t9.*(m1.*ydot+m2.*ydot+m3.*ydot+d1.*m1.*q1dot.*t3+d2.*m2.*q1dot.*t10-d2.*m2.*q2dot.*t10+l1.*m2.*q1dot.*t3-d3.*m3.*q3dot.*sin(q3))];
end
