function h_flight = auto_h_flight(q1,q2,qd1,qd2)
%AUTO_H_FLIGHT
%    H_FLIGHT = AUTO_H_FLIGHT(Q1,Q2,QD1,QD2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Oct-2025 09:33:06

h_flight = [q1-qd1;q2-qd2];
end
