function Jhdot_flight = auto_Jhdot_flight
%auto_Jhdot_flight
%    Jhdot_flight = auto_Jhdot_flight

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Oct-2025 09:33:06

Jhdot_flight = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
end
