function D = auto_D(I1,I2,I3,d1,d2,d3,l1,m1,m2,m3,q1,q2,q3)
%auto_D
%    D = auto_D(I1,I2,I3,D1,D2,D3,L1,M1,M2,M3,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:31

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q3);
t7 = d2.^2;
t8 = m1+m2+m3;
t9 = -I2;
t10 = -q2;
t11 = d1.*m1.*t2;
t12 = d3.*m3.*t4;
t13 = d1.*m1.*t5;
t14 = d3.*m3.*t6;
t15 = m2.*t7;
t16 = l1.*t2.*2.0;
t17 = l1.*t5.*2.0;
t18 = d2.*l1.*m2.*t3;
t19 = q1+t10;
t20 = cos(t19);
t21 = -t11;
t22 = -t12;
t23 = sin(t19);
t24 = -t14;
t25 = -t15;
t26 = -t18;
t27 = d2.*m2.*t20;
t28 = d2.*m2.*t23;
t29 = d2.*t20.*2.0;
t30 = d2.*t23.*2.0;
t34 = t9+t25+t26;
t31 = -t28;
t32 = t16+t29;
t33 = t17+t30;
t35 = (m2.*t32)./2.0;
t36 = (m2.*t33)./2.0;
t37 = -t35;
t38 = t13+t36;
t39 = t21+t37;
D = reshape([t8,0.0,t39,t27,t22,0.0,t8,t38,t31,t24,t39,t38,I1+I2+t15+t18.*2.0+d1.^2.*m1+l1.^2.*m2,t34,0.0,t27,t31,t34,I2+t15,0.0,t22,t24,0.0,0.0,I3+d3.^2.*m3],[5,5]);
end
