function Jstdot = auto_Jstdot(l1,l2,q1,q2,q1dot,q2dot)
%auto_Jstdot
%    Jstdot = auto_Jstdot(L1,L2,Q1,Q2,Q1DOT,Q2DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

t2 = -q2;
t3 = -q2dot;
t4 = q1+t2;
t5 = q1dot+t3;
t6 = cos(t4);
t7 = sin(t4);
Jstdot = reshape([0.0,0.0,0.0,0.0,q1dot.*(l2.*t7+l1.*sin(q1))+l2.*t3.*t7,q1dot.*(l2.*t6+l1.*cos(q1))+l2.*t3.*t6,-l2.*t5.*t7,-l2.*t5.*t6,0.0,0.0],[2,5]);
end
