function h = auto_h(d1,d2,d3,l1,l2,m1,m2,m3,pCOMy_d,q1,q2,q3,x,y)
%AUTO_H
%    H = AUTO_H(D1,D2,D3,L1,L2,M1,M2,M3,pCOMy_d,Q1,Q2,Q3,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

t2 = cos(q1);
t3 = sin(q1);
t4 = m1+m2+m3;
t6 = -q2;
t7 = -x;
t5 = l1.*t3;
t8 = q1+t6;
t9 = 1.0./t4;
t10 = sin(t8);
h = [t5+t7+l2.*t10+t9.*(-m2.*(t5+t7+d2.*t10)+m3.*(x-d3.*sin(q3))+m1.*(x-d1.*t3));-pCOMy_d+t9.*(m3.*(y+d3.*cos(q3))+m1.*(y-d1.*t2)-m2.*(-y+l1.*t2+d2.*cos(t8)))];
end
