function Jh = auto_Jh(d1,d2,d3,l1,l2,m1,m2,m3,q1,q2,q3)
%auto_Jh
%    Jh = auto_Jh(D1,D2,D3,L1,L2,M1,M2,M3,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

t2 = cos(q1);
t3 = sin(q1);
t5 = m1+m2+m3;
t6 = -q2;
t4 = l1.*t2;
t7 = q1+t6;
t9 = 1.0./t5;
t8 = cos(t7);
t10 = sin(t7);
t11 = l2.*t8;
Jh = reshape([0.0,0.0,0.0,1.0,t4+t11-t9.*(m2.*(t4+d2.*t8)+d1.*m1.*t2),t9.*(m2.*(d2.*t10+l1.*t3)+d1.*m1.*t3),-t11+d2.*m2.*t8.*t9,-d2.*m2.*t9.*t10,-d3.*m3.*t9.*cos(q3),-d3.*m3.*t9.*sin(q3)],[2,5]);
end
