function Jhdotdq = auto_Jhdotdq(d1,d2,d3,l1,l2,m1,m2,m3,q1,q2,q3,q1dot,q2dot,q3dot)
%auto_Jhdotdq
%    Jhdotdq = auto_Jhdotdq(D1,D2,D3,L1,L2,M1,M2,M3,Q1,Q2,Q3,Q1DOT,Q2DOT,Q3DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

t2 = cos(q1);
t3 = sin(q1);
t4 = q1dot.^2;
t5 = q3dot.^2;
t6 = m1+m2+m3;
t8 = -q2;
t7 = l1.*t3;
t9 = q1+t8;
t11 = 1.0./t6;
t10 = cos(t9);
t12 = sin(t9);
t13 = l2.*t12;
t14 = d2.*m2.*t11.*t12;
t15 = -t14;
t16 = t13+t15;
t17 = q2dot.*t16;
Jhdotdq = [q1dot.*(t17-q1dot.*(t7+t13-t11.*(m2.*(t7+d2.*t12)+d1.*m1.*t3)))-q2dot.*(t17-q1dot.*t16)+d3.*m3.*t5.*t11.*sin(q3);t11.*(d1.*m1.*t2.*t4+d2.*m2.*t4.*t10+l1.*m2.*t2.*t4+d2.*m2.*q2dot.^2.*t10-d3.*m3.*t5.*cos(q3)-d2.*m2.*q1dot.*q2dot.*t10.*2.0)];
end
