function Jhdotdq_flight = auto_Jhdotdq_flight
%auto_Jhdotdq_flight
%    Jhdotdq_flight = auto_Jhdotdq_flight

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Oct-2025 09:33:06

Jhdotdq_flight = [0.0;0.0];
end
