function dJpCOM = auto_dJpCOM(d1,d2,d3,l1,m1,m2,m3,q1,q2,q3,q1dot,q2dot,q3dot)
%auto_dJpCOM
%    dJpCOM = auto_dJpCOM(D1,D2,D3,L1,M1,M2,M3,Q1,Q2,Q3,Q1DOT,Q2DOT,Q3DOT)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    26-Oct-2025 22:41:32

t2 = cos(q1);
t3 = sin(q1);
t4 = m1+m2+m3;
t5 = -q2;
t6 = -q2dot;
t7 = q1+t5;
t8 = q1dot+t6;
t10 = 1.0./t4;
t9 = cos(t7);
t11 = sin(t7);
dJpCOM = reshape([0.0,0.0,0.0,0.0,q1dot.*t10.*(m2.*(d2.*t11+l1.*t3)+d1.*m1.*t3)+d2.*m2.*t6.*t10.*t11,q1dot.*t10.*(m2.*(d2.*t9+l1.*t2)+d1.*m1.*t2)+d2.*m2.*t6.*t9.*t10,-d2.*m2.*t8.*t10.*t11,-d2.*m2.*t8.*t9.*t10,d3.*m3.*q3dot.*t10.*sin(q3),-d3.*m3.*q3dot.*t10.*cos(q3)],[2,5]);
end
