function Jh_flight = auto_Jh_flight
%auto_Jh_flight
%    Jh_flight = auto_Jh_flight

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Oct-2025 09:33:06

Jh_flight = reshape([0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0],[2,5]);
end
